// SESSION CONFIGURATION
const SESSION_MAX_AGE = 30 * 24 * 60 * 60; // 30 DAYS

// JWT TOKEN AGE
const ACCESS_TOKEN_MAX_AGE = 15 * 60; // 15 MIN
const REFRESH_TOKEN_MAX_AGE = 30 * 24 * 60 * 60; // 30 DAYS

module.exports = { SESSION_MAX_AGE, ACCESS_TOKEN_MAX_AGE, REFRESH_TOKEN_MAX_AGE };